[[news]]
date = "2025"
content = "11-04: New paper published in The Journal of Chemical Physics - [“Accelerating energy minimization process in charged polymer–biomolecular systems: An enhanced nonlinear conjugate gradient method”]"


[[news]]
date = "2025"
content = "09-29: Awarded the Hua Luogeng Scholarship at AMSS 🎖️"
